global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'log-producer'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/producer/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'log-consumer'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/gateway/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka:9101']
