global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'log-producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.18.48.1:8081']

  - job_name: 'log-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.18.48.1:8082']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.18.48.1:8080']
