server:
  port: 8082

spring:
  application:
    name: log-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    listener:
      ack-mode: manual-immediate
  
  datasource:
    url: jdbc:postgresql://localhost:5432/logprocessor
    username: loguser
    password: logpassword
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# Circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      database:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        sliding-window-size: 10

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    com.example.logprocessor: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
