server:
  port: 8082

spring:
  application:
    name: log-receiver
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

# TCP Server Configuration
tcp:
  server:
    port: 9090
    thread-pool-size: 10

# Kafka Configuration
kafka:
  topic: logs

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example.logreceiver: DEBUG
    org.springframework.kafka: INFO
