server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: log-producer

# UDP Configuration
udp:
  server:
    host: localhost
    port: 9876
  retry:
    max: 3
  timeout:
    seconds: 5

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example.logprocessor: DEBUG
