FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY common common/
COPY map-worker map-worker/
RUN mvn clean package -pl map-worker -am -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/map-worker/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
