FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY common common/
COPY mapreduce-coordinator mapreduce-coordinator/
RUN mvn clean package -pl mapreduce-coordinator -am -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/mapreduce-coordinator/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
