server:
  port: 8081

spring:
  application:
    name: log-producer

log:
  shipper:
    url: http://log-shipper:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
