server:
  port: 8082
  address: 0.0.0.0

spring:
  application:
    name: log-consumer
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  
  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/logdb
    username: loguser
    password: logpass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

# UDP Server Configuration
udp:
  server:
    port: 9876
  buffer:
    size: 26214400

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example.logprocessor: DEBUG
