server:
  port: 8081

spring:
  application:
    name: log-producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: 1
      retries: 3
      batch-size: 16384
      linger-ms: 10
      compression-type: none  # We handle compression ourselves

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example.logprocessor: DEBUG
