package com.example.logprocessor.producer;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;

@Service
@Slf4j
public class LoadGeneratorService {
    
    private final KafkaProducerService producerService;
    private final ExecutorService steadyLoadExecutor;
    private final ExecutorService burstLoadExecutor;
    private final AtomicBoolean isRunning;
    private final AtomicLong generatedCount;
    private final Counter generatedCounter;
    
    @Value("${load.generator.steady.rate:1000}")
    private int steadyRate;
    
    @Value("${load.generator.burst.rate:10000}")
    private int burstRate;
    
    @Value("${load.generator.enabled:false}")
    private boolean enabled;
    
    private static final List<String> LOG_LEVELS = List.of("INFO", "WARN", "ERROR", "DEBUG");
    private static final List<String> SOURCES = List.of("api-gateway", "auth-service", "payment-service", "user-service");

    public LoadGeneratorService(KafkaProducerService producerService, MeterRegistry meterRegistry) {
        this.producerService = producerService;
        this.steadyLoadExecutor = Executors.newFixedThreadPool(10);
        this.burstLoadExecutor = Executors.newFixedThreadPool(50);
        this.isRunning = new AtomicBoolean(false);
        this.generatedCount = new AtomicLong(0);
        this.generatedCounter = Counter.builder("load.generator.logs.generated")
                .description("Total logs generated by load generator")
                .register(meterRegistry);
    }

    @PostConstruct
    public void init() {
        if (enabled) {
            log.info("Load generator enabled with steady rate: {}/sec, burst rate: {}/sec", 
                    steadyRate, burstRate);
        } else {
            log.info("Load generator disabled. Enable with load.generator.enabled=true");
        }
    }

    // Steady load generation - runs continuously
    @Scheduled(fixedRate = 1000)
    public void generateSteadyLoad() {
        if (!enabled || !isRunning.compareAndSet(false, true)) {
            return;
        }
        
        try {
            List<CompletableFuture<Void>> futures = new ArrayList<>();
            int logsPerSecond = steadyRate;
            
            for (int i = 0; i < logsPerSecond; i++) {
                CompletableFuture<Void> future = CompletableFuture.runAsync(() -> {
                    LogEvent event = generateLogEvent();
                    producerService.sendLog(event);
                    generatedCounter.increment();
                    generatedCount.incrementAndGet();
                }, steadyLoadExecutor);
                futures.add(future);
            }
            
            // Wait for all sends to complete
            CompletableFuture.allOf(futures.toArray(new CompletableFuture[0])).join();
            
        } catch (Exception e) {
            log.error("Error generating steady load", e);
        } finally {
            isRunning.set(false);
        }
    }

    // Burst load generation - simulate traffic spikes
    public void generateBurst(int durationSeconds) {
        log.info("Starting burst load generation for {} seconds at {} logs/sec", 
                durationSeconds, burstRate);
        
        CompletableFuture.runAsync(() -> {
            long endTime = System.currentTimeMillis() + (durationSeconds * 1000L);
            
            while (System.currentTimeMillis() < endTime) {
                long startMillis = System.currentTimeMillis();
                List<CompletableFuture<Void>> futures = new ArrayList<>();
                
                for (int i = 0; i < burstRate; i++) {
                    CompletableFuture<Void> future = CompletableFuture.runAsync(() -> {
                        LogEvent event = generateLogEvent();
                        producerService.sendLog(event);
                        generatedCounter.increment();
                        generatedCount.incrementAndGet();
                    }, burstLoadExecutor);
                    futures.add(future);
                }
                
                // Wait for all sends in this second
                CompletableFuture.allOf(futures.toArray(new CompletableFuture[0])).join();
                
                // Sleep for remainder of second
                long elapsed = System.currentTimeMillis() - startMillis;
                if (elapsed < 1000) {
                    try {
                        Thread.sleep(1000 - elapsed);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        break;
                    }
                }
            }
            
            log.info("Burst load generation completed");
        }, burstLoadExecutor);
    }

    private LogEvent generateLogEvent() {
        return LogEvent.builder()
                .id(UUID.randomUUID().toString())
                .level(LOG_LEVELS.get(ThreadLocalRandom.current().nextInt(LOG_LEVELS.size())))
                .message(generateMessage())
                .source(SOURCES.get(ThreadLocalRandom.current().nextInt(SOURCES.size())))
                .timestamp(Instant.now())
                .traceId(UUID.randomUUID().toString())
                .build();
    }

    private String generateMessage() {
        return "Load test message at " + Instant.now() + " - " + UUID.randomUUID();
    }

    public long getGeneratedCount() {
        return generatedCount.get();
    }

    public void resetCount() {
        generatedCount.set(0);
    }

    @PreDestroy
    public void shutdown() {
        log.info("Shutting down load generator");
        steadyLoadExecutor.shutdown();
        burstLoadExecutor.shutdown();
        try {
            if (!steadyLoadExecutor.awaitTermination(30, TimeUnit.SECONDS)) {
                steadyLoadExecutor.shutdownNow();
            }
            if (!burstLoadExecutor.awaitTermination(30, TimeUnit.SECONDS)) {
                burstLoadExecutor.shutdownNow();
            }
        } catch (InterruptedException e) {
            steadyLoadExecutor.shutdownNow();
            burstLoadExecutor.shutdownNow();
            Thread.currentThread().interrupt();
        }
    }
}
