server:
  port: 8081

spring:
  application:
    name: log-producer
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  jackson:
    serialization:
      write-dates-as-timestamps: false

# Custom application properties
app:
  kafka:
    topic:
      log-events: log-events

# Circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      kafka-producer:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        sliding-window-size: 10
        minimum-number-of-calls: 5

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    com.example.logprocessor: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
