server:
  port: 8082

spring:
  application:
    name: log-consumer
  
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: log-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 100
      properties:
        isolation.level: read_committed
    
    listener:
      ack-mode: manual

  datasource:
    url: jdbc:postgresql://postgres:5432/logdb
    username: loguser
    password: logpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.logprocessor: INFO
    org.springframework.kafka: WARN
    org.hibernate.SQL: WARN
