/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.logprocessor.common.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LogEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6577065862479192065L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LogEvent\",\"namespace\":\"com.example.logprocessor.common.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"level\",\"type\":\"string\"},{\"name\":\"service\",\"type\":\"string\"},{\"name\":\"host\",\"type\":\"string\"},{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"traceId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"spanId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"metadata\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"default\":{}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LogEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LogEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LogEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LogEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LogEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LogEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LogEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LogEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LogEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private long timestamp;
  private java.lang.CharSequence level;
  private java.lang.CharSequence service;
  private java.lang.CharSequence host;
  private java.lang.CharSequence message;
  private java.lang.CharSequence traceId;
  private java.lang.CharSequence spanId;
  private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LogEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param timestamp The new value for timestamp
   * @param level The new value for level
   * @param service The new value for service
   * @param host The new value for host
   * @param message The new value for message
   * @param traceId The new value for traceId
   * @param spanId The new value for spanId
   * @param metadata The new value for metadata
   */
  public LogEvent(java.lang.CharSequence id, java.lang.Long timestamp, java.lang.CharSequence level, java.lang.CharSequence service, java.lang.CharSequence host, java.lang.CharSequence message, java.lang.CharSequence traceId, java.lang.CharSequence spanId, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata) {
    this.id = id;
    this.timestamp = timestamp;
    this.level = level;
    this.service = service;
    this.host = host;
    this.message = message;
    this.traceId = traceId;
    this.spanId = spanId;
    this.metadata = metadata;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return timestamp;
    case 2: return level;
    case 3: return service;
    case 4: return host;
    case 5: return message;
    case 6: return traceId;
    case 7: return spanId;
    case 8: return metadata;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: level = (java.lang.CharSequence)value$; break;
    case 3: service = (java.lang.CharSequence)value$; break;
    case 4: host = (java.lang.CharSequence)value$; break;
    case 5: message = (java.lang.CharSequence)value$; break;
    case 6: traceId = (java.lang.CharSequence)value$; break;
    case 7: spanId = (java.lang.CharSequence)value$; break;
    case 8: metadata = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'level' field.
   * @return The value of the 'level' field.
   */
  public java.lang.CharSequence getLevel() {
    return level;
  }


  /**
   * Sets the value of the 'level' field.
   * @param value the value to set.
   */
  public void setLevel(java.lang.CharSequence value) {
    this.level = value;
  }

  /**
   * Gets the value of the 'service' field.
   * @return The value of the 'service' field.
   */
  public java.lang.CharSequence getService() {
    return service;
  }


  /**
   * Sets the value of the 'service' field.
   * @param value the value to set.
   */
  public void setService(java.lang.CharSequence value) {
    this.service = value;
  }

  /**
   * Gets the value of the 'host' field.
   * @return The value of the 'host' field.
   */
  public java.lang.CharSequence getHost() {
    return host;
  }


  /**
   * Sets the value of the 'host' field.
   * @param value the value to set.
   */
  public void setHost(java.lang.CharSequence value) {
    this.host = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'traceId' field.
   * @return The value of the 'traceId' field.
   */
  public java.lang.CharSequence getTraceId() {
    return traceId;
  }


  /**
   * Sets the value of the 'traceId' field.
   * @param value the value to set.
   */
  public void setTraceId(java.lang.CharSequence value) {
    this.traceId = value;
  }

  /**
   * Gets the value of the 'spanId' field.
   * @return The value of the 'spanId' field.
   */
  public java.lang.CharSequence getSpanId() {
    return spanId;
  }


  /**
   * Sets the value of the 'spanId' field.
   * @param value the value to set.
   */
  public void setSpanId(java.lang.CharSequence value) {
    this.spanId = value;
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return The value of the 'metadata' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
    return metadata;
  }


  /**
   * Sets the value of the 'metadata' field.
   * @param value the value to set.
   */
  public void setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.metadata = value;
  }

  /**
   * Creates a new LogEvent RecordBuilder.
   * @return A new LogEvent RecordBuilder
   */
  public static com.example.logprocessor.common.avro.LogEvent.Builder newBuilder() {
    return new com.example.logprocessor.common.avro.LogEvent.Builder();
  }

  /**
   * Creates a new LogEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LogEvent RecordBuilder
   */
  public static com.example.logprocessor.common.avro.LogEvent.Builder newBuilder(com.example.logprocessor.common.avro.LogEvent.Builder other) {
    if (other == null) {
      return new com.example.logprocessor.common.avro.LogEvent.Builder();
    } else {
      return new com.example.logprocessor.common.avro.LogEvent.Builder(other);
    }
  }

  /**
   * Creates a new LogEvent RecordBuilder by copying an existing LogEvent instance.
   * @param other The existing instance to copy.
   * @return A new LogEvent RecordBuilder
   */
  public static com.example.logprocessor.common.avro.LogEvent.Builder newBuilder(com.example.logprocessor.common.avro.LogEvent other) {
    if (other == null) {
      return new com.example.logprocessor.common.avro.LogEvent.Builder();
    } else {
      return new com.example.logprocessor.common.avro.LogEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for LogEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LogEvent>
    implements org.apache.avro.data.RecordBuilder<LogEvent> {

    private java.lang.CharSequence id;
    private long timestamp;
    private java.lang.CharSequence level;
    private java.lang.CharSequence service;
    private java.lang.CharSequence host;
    private java.lang.CharSequence message;
    private java.lang.CharSequence traceId;
    private java.lang.CharSequence spanId;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.logprocessor.common.avro.LogEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.level)) {
        this.level = data().deepCopy(fields()[2].schema(), other.level);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.service)) {
        this.service = data().deepCopy(fields()[3].schema(), other.service);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.host)) {
        this.host = data().deepCopy(fields()[4].schema(), other.host);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.message)) {
        this.message = data().deepCopy(fields()[5].schema(), other.message);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.traceId)) {
        this.traceId = data().deepCopy(fields()[6].schema(), other.traceId);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.spanId)) {
        this.spanId = data().deepCopy(fields()[7].schema(), other.spanId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.metadata)) {
        this.metadata = data().deepCopy(fields()[8].schema(), other.metadata);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing LogEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.logprocessor.common.avro.LogEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.level)) {
        this.level = data().deepCopy(fields()[2].schema(), other.level);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.service)) {
        this.service = data().deepCopy(fields()[3].schema(), other.service);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.host)) {
        this.host = data().deepCopy(fields()[4].schema(), other.host);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.message)) {
        this.message = data().deepCopy(fields()[5].schema(), other.message);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.traceId)) {
        this.traceId = data().deepCopy(fields()[6].schema(), other.traceId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.spanId)) {
        this.spanId = data().deepCopy(fields()[7].schema(), other.spanId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.metadata)) {
        this.metadata = data().deepCopy(fields()[8].schema(), other.metadata);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'level' field.
      * @return The value.
      */
    public java.lang.CharSequence getLevel() {
      return level;
    }


    /**
      * Sets the value of the 'level' field.
      * @param value The value of 'level'.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder setLevel(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.level = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'level' field has been set.
      * @return True if the 'level' field has been set, false otherwise.
      */
    public boolean hasLevel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'level' field.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder clearLevel() {
      level = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'service' field.
      * @return The value.
      */
    public java.lang.CharSequence getService() {
      return service;
    }


    /**
      * Sets the value of the 'service' field.
      * @param value The value of 'service'.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder setService(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.service = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'service' field has been set.
      * @return True if the 'service' field has been set, false otherwise.
      */
    public boolean hasService() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'service' field.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder clearService() {
      service = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'host' field.
      * @return The value.
      */
    public java.lang.CharSequence getHost() {
      return host;
    }


    /**
      * Sets the value of the 'host' field.
      * @param value The value of 'host'.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder setHost(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.host = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'host' field has been set.
      * @return True if the 'host' field has been set, false otherwise.
      */
    public boolean hasHost() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'host' field.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder clearHost() {
      host = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.message = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder clearMessage() {
      message = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'traceId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTraceId() {
      return traceId;
    }


    /**
      * Sets the value of the 'traceId' field.
      * @param value The value of 'traceId'.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder setTraceId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.traceId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'traceId' field has been set.
      * @return True if the 'traceId' field has been set, false otherwise.
      */
    public boolean hasTraceId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'traceId' field.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder clearTraceId() {
      traceId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'spanId' field.
      * @return The value.
      */
    public java.lang.CharSequence getSpanId() {
      return spanId;
    }


    /**
      * Sets the value of the 'spanId' field.
      * @param value The value of 'spanId'.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder setSpanId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.spanId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'spanId' field has been set.
      * @return True if the 'spanId' field has been set, false otherwise.
      */
    public boolean hasSpanId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'spanId' field.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder clearSpanId() {
      spanId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[8], value);
      this.metadata = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'metadata' field.
      * @return This builder.
      */
    public com.example.logprocessor.common.avro.LogEvent.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LogEvent build() {
      try {
        LogEvent record = new LogEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.level = fieldSetFlags()[2] ? this.level : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.service = fieldSetFlags()[3] ? this.service : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.host = fieldSetFlags()[4] ? this.host : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.message = fieldSetFlags()[5] ? this.message : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.traceId = fieldSetFlags()[6] ? this.traceId : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.spanId = fieldSetFlags()[7] ? this.spanId : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.metadata = fieldSetFlags()[8] ? this.metadata : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LogEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<LogEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LogEvent>
    READER$ = (org.apache.avro.io.DatumReader<LogEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeLong(this.timestamp);

    out.writeString(this.level);

    out.writeString(this.service);

    out.writeString(this.host);

    out.writeString(this.message);

    if (this.traceId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.traceId);
    }

    if (this.spanId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.spanId);
    }

    long size0 = this.metadata.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, java.lang.CharSequence> e0: this.metadata.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.CharSequence v0 = e0.getValue();
      out.writeString(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.timestamp = in.readLong();

      this.level = in.readString(this.level instanceof Utf8 ? (Utf8)this.level : null);

      this.service = in.readString(this.service instanceof Utf8 ? (Utf8)this.service : null);

      this.host = in.readString(this.host instanceof Utf8 ? (Utf8)this.host : null);

      this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.traceId = null;
      } else {
        this.traceId = in.readString(this.traceId instanceof Utf8 ? (Utf8)this.traceId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.spanId = null;
      } else {
        this.spanId = in.readString(this.spanId instanceof Utf8 ? (Utf8)this.spanId : null);
      }

      long size0 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m0 = this.metadata; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size0);
        this.metadata = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence k0 = null;
          k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
          java.lang.CharSequence v0 = null;
          v0 = in.readString(v0 instanceof Utf8 ? (Utf8)v0 : null);
          m0.put(k0, v0);
        }
      }

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.level = in.readString(this.level instanceof Utf8 ? (Utf8)this.level : null);
          break;

        case 3:
          this.service = in.readString(this.service instanceof Utf8 ? (Utf8)this.service : null);
          break;

        case 4:
          this.host = in.readString(this.host instanceof Utf8 ? (Utf8)this.host : null);
          break;

        case 5:
          this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.traceId = null;
          } else {
            this.traceId = in.readString(this.traceId instanceof Utf8 ? (Utf8)this.traceId : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.spanId = null;
          } else {
            this.spanId = in.readString(this.spanId instanceof Utf8 ? (Utf8)this.spanId : null);
          }
          break;

        case 8:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m0 = this.metadata; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size0);
            this.metadata = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence k0 = null;
              k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
              java.lang.CharSequence v0 = null;
              v0 = in.readString(v0 instanceof Utf8 ? (Utf8)v0 : null);
              m0.put(k0, v0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










