/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.logprocessor.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Log event schema version 1 - baseline schema */
@org.apache.avro.specific.AvroGenerated
public class LogEventV1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4686144803739444176L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LogEventV1\",\"namespace\":\"com.example.logprocessor.avro\",\"doc\":\"Log event schema version 1 - baseline schema\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique event identifier\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Event timestamp in milliseconds since epoch\"},{\"name\":\"level\",\"type\":{\"type\":\"enum\",\"name\":\"LogLevel\",\"symbols\":[\"TRACE\",\"DEBUG\",\"INFO\",\"WARN\",\"ERROR\",\"FATAL\"]},\"doc\":\"Log severity level\"},{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Log message content\"},{\"name\":\"source\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Service or component that generated the log\"},{\"name\":\"schemaVersion\",\"type\":\"int\",\"doc\":\"Schema version for debugging\",\"default\":1}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LogEventV1> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LogEventV1> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LogEventV1> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LogEventV1> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LogEventV1> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LogEventV1 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LogEventV1 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LogEventV1 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LogEventV1 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique event identifier */
  private java.lang.String id;
  /** Event timestamp in milliseconds since epoch */
  private long timestamp;
  /** Log severity level */
  private com.example.logprocessor.avro.LogLevel level;
  /** Log message content */
  private java.lang.String message;
  /** Service or component that generated the log */
  private java.lang.String source;
  /** Schema version for debugging */
  private int schemaVersion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LogEventV1() {}

  /**
   * All-args constructor.
   * @param id Unique event identifier
   * @param timestamp Event timestamp in milliseconds since epoch
   * @param level Log severity level
   * @param message Log message content
   * @param source Service or component that generated the log
   * @param schemaVersion Schema version for debugging
   */
  public LogEventV1(java.lang.String id, java.lang.Long timestamp, com.example.logprocessor.avro.LogLevel level, java.lang.String message, java.lang.String source, java.lang.Integer schemaVersion) {
    this.id = id;
    this.timestamp = timestamp;
    this.level = level;
    this.message = message;
    this.source = source;
    this.schemaVersion = schemaVersion;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return timestamp;
    case 2: return level;
    case 3: return message;
    case 4: return source;
    case 5: return schemaVersion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: level = (com.example.logprocessor.avro.LogLevel)value$; break;
    case 3: message = value$ != null ? value$.toString() : null; break;
    case 4: source = value$ != null ? value$.toString() : null; break;
    case 5: schemaVersion = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Unique event identifier
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * Unique event identifier
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Event timestamp in milliseconds since epoch
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Event timestamp in milliseconds since epoch
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'level' field.
   * @return Log severity level
   */
  public com.example.logprocessor.avro.LogLevel getLevel() {
    return level;
  }


  /**
   * Sets the value of the 'level' field.
   * Log severity level
   * @param value the value to set.
   */
  public void setLevel(com.example.logprocessor.avro.LogLevel value) {
    this.level = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return Log message content
   */
  public java.lang.String getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * Log message content
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return Service or component that generated the log
   */
  public java.lang.String getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * Service or component that generated the log
   * @param value the value to set.
   */
  public void setSource(java.lang.String value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'schemaVersion' field.
   * @return Schema version for debugging
   */
  public int getSchemaVersion() {
    return schemaVersion;
  }


  /**
   * Sets the value of the 'schemaVersion' field.
   * Schema version for debugging
   * @param value the value to set.
   */
  public void setSchemaVersion(int value) {
    this.schemaVersion = value;
  }

  /**
   * Creates a new LogEventV1 RecordBuilder.
   * @return A new LogEventV1 RecordBuilder
   */
  public static com.example.logprocessor.avro.LogEventV1.Builder newBuilder() {
    return new com.example.logprocessor.avro.LogEventV1.Builder();
  }

  /**
   * Creates a new LogEventV1 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LogEventV1 RecordBuilder
   */
  public static com.example.logprocessor.avro.LogEventV1.Builder newBuilder(com.example.logprocessor.avro.LogEventV1.Builder other) {
    if (other == null) {
      return new com.example.logprocessor.avro.LogEventV1.Builder();
    } else {
      return new com.example.logprocessor.avro.LogEventV1.Builder(other);
    }
  }

  /**
   * Creates a new LogEventV1 RecordBuilder by copying an existing LogEventV1 instance.
   * @param other The existing instance to copy.
   * @return A new LogEventV1 RecordBuilder
   */
  public static com.example.logprocessor.avro.LogEventV1.Builder newBuilder(com.example.logprocessor.avro.LogEventV1 other) {
    if (other == null) {
      return new com.example.logprocessor.avro.LogEventV1.Builder();
    } else {
      return new com.example.logprocessor.avro.LogEventV1.Builder(other);
    }
  }

  /**
   * RecordBuilder for LogEventV1 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LogEventV1>
    implements org.apache.avro.data.RecordBuilder<LogEventV1> {

    /** Unique event identifier */
    private java.lang.String id;
    /** Event timestamp in milliseconds since epoch */
    private long timestamp;
    /** Log severity level */
    private com.example.logprocessor.avro.LogLevel level;
    /** Log message content */
    private java.lang.String message;
    /** Service or component that generated the log */
    private java.lang.String source;
    /** Schema version for debugging */
    private int schemaVersion;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.logprocessor.avro.LogEventV1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.level)) {
        this.level = data().deepCopy(fields()[2].schema(), other.level);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.message)) {
        this.message = data().deepCopy(fields()[3].schema(), other.message);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.source)) {
        this.source = data().deepCopy(fields()[4].schema(), other.source);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.schemaVersion)) {
        this.schemaVersion = data().deepCopy(fields()[5].schema(), other.schemaVersion);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing LogEventV1 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.logprocessor.avro.LogEventV1 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.level)) {
        this.level = data().deepCopy(fields()[2].schema(), other.level);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.message)) {
        this.message = data().deepCopy(fields()[3].schema(), other.message);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.source)) {
        this.source = data().deepCopy(fields()[4].schema(), other.source);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.schemaVersion)) {
        this.schemaVersion = data().deepCopy(fields()[5].schema(), other.schemaVersion);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Unique event identifier
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * Unique event identifier
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Unique event identifier
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Unique event identifier
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Event timestamp in milliseconds since epoch
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Event timestamp in milliseconds since epoch
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Event timestamp in milliseconds since epoch
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Event timestamp in milliseconds since epoch
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'level' field.
      * Log severity level
      * @return The value.
      */
    public com.example.logprocessor.avro.LogLevel getLevel() {
      return level;
    }


    /**
      * Sets the value of the 'level' field.
      * Log severity level
      * @param value The value of 'level'.
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder setLevel(com.example.logprocessor.avro.LogLevel value) {
      validate(fields()[2], value);
      this.level = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'level' field has been set.
      * Log severity level
      * @return True if the 'level' field has been set, false otherwise.
      */
    public boolean hasLevel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'level' field.
      * Log severity level
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder clearLevel() {
      level = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * Log message content
      * @return The value.
      */
    public java.lang.String getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * Log message content
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder setMessage(java.lang.String value) {
      validate(fields()[3], value);
      this.message = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * Log message content
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'message' field.
      * Log message content
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder clearMessage() {
      message = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * Service or component that generated the log
      * @return The value.
      */
    public java.lang.String getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * Service or component that generated the log
      * @param value The value of 'source'.
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder setSource(java.lang.String value) {
      validate(fields()[4], value);
      this.source = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * Service or component that generated the log
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'source' field.
      * Service or component that generated the log
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder clearSource() {
      source = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'schemaVersion' field.
      * Schema version for debugging
      * @return The value.
      */
    public int getSchemaVersion() {
      return schemaVersion;
    }


    /**
      * Sets the value of the 'schemaVersion' field.
      * Schema version for debugging
      * @param value The value of 'schemaVersion'.
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder setSchemaVersion(int value) {
      validate(fields()[5], value);
      this.schemaVersion = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'schemaVersion' field has been set.
      * Schema version for debugging
      * @return True if the 'schemaVersion' field has been set, false otherwise.
      */
    public boolean hasSchemaVersion() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'schemaVersion' field.
      * Schema version for debugging
      * @return This builder.
      */
    public com.example.logprocessor.avro.LogEventV1.Builder clearSchemaVersion() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LogEventV1 build() {
      try {
        LogEventV1 record = new LogEventV1();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.level = fieldSetFlags()[2] ? this.level : (com.example.logprocessor.avro.LogLevel) defaultValue(fields()[2]);
        record.message = fieldSetFlags()[3] ? this.message : (java.lang.String) defaultValue(fields()[3]);
        record.source = fieldSetFlags()[4] ? this.source : (java.lang.String) defaultValue(fields()[4]);
        record.schemaVersion = fieldSetFlags()[5] ? this.schemaVersion : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LogEventV1>
    WRITER$ = (org.apache.avro.io.DatumWriter<LogEventV1>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LogEventV1>
    READER$ = (org.apache.avro.io.DatumReader<LogEventV1>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeLong(this.timestamp);

    out.writeEnum(this.level.ordinal());

    out.writeString(this.message);

    out.writeString(this.source);

    out.writeInt(this.schemaVersion);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.timestamp = in.readLong();

      this.level = com.example.logprocessor.avro.LogLevel.values()[in.readEnum()];

      this.message = in.readString();

      this.source = in.readString();

      this.schemaVersion = in.readInt();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.level = com.example.logprocessor.avro.LogLevel.values()[in.readEnum()];
          break;

        case 3:
          this.message = in.readString();
          break;

        case 4:
          this.source = in.readString();
          break;

        case 5:
          this.schemaVersion = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










