/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.logprocessor.avro;
@org.apache.avro.specific.AvroGenerated
public enum LogLevel implements org.apache.avro.generic.GenericEnumSymbol<LogLevel> {
  TRACE, DEBUG, INFO, WARN, ERROR, FATAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LogLevel\",\"namespace\":\"com.example.logprocessor.avro\",\"symbols\":[\"TRACE\",\"DEBUG\",\"INFO\",\"WARN\",\"ERROR\",\"FATAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
